# Generated by Django 6.0.2 on 2026-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_deadline_remove_job_job_type_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
