# Generated by Django 6.0.2 on 2026-03-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_aptitude_passed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_website',
        ),
    ]
