# Generated by Django 6.0.3 on 2026-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
    ]
