# Generated by Django 6.0.3 on 2026-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employerprofile_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='daily_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
