# Generated by Django 6.0.3 on 2026-04-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='college_id',
            field=models.FileField(blank=True, help_text='Upload College ID for verification', null=True, upload_to='mentors/id_cards/'),
        ),
    ]
