# Generated by Django 6.0.3 on 2026-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_mentorprofile_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for direct contact', max_length=20),
        ),
    ]
