# Generated by Django 6.0.2 on 2026-03-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_make_student_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationdocument',
            unique_together=set(),
        ),
    ]
