# Generated by Django 6.0.3 on 2026-03-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_job_course_description_course_duration_course_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
