# Generated by Django 6.0.3 on 2026-03-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student'),
        ('courses', '0003_certificate_pdf_alter_certificate_certificate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
    ]
