# Generated by Django 6.0.3 on 2026-03-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseprogress_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default='2026-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('freelance', 'Freelance')], default='internship', max_length=20),
            preserve_default=False,
        ),
    ]
