# Generated by Django 6.0.3 on 2026-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_job_skills_remove_job_type_job_deadline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(default='issued', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='target_program',
            field=models.CharField(choices=[('BTech', 'B.Tech'), ('BCA', 'BCA'), ('BCom', 'B.Com'), ('BBA', 'BBA'), ('Any', 'Any Program')], default='Any', max_length=20),
        ),
    ]
